### ISSUE TITLE
Mix of data and Metadata

### ISSUE THREAD

**Issue by physikerwelt** [w3c/mathml-docs#81]
https://github.com/w3c/mathml-docs/blob/cb9e988108be0cd216b9f024863cd6f2715d5552/_data/core.yml#L472-L473

When I wanted to import speech tags from the core list, I realized that there is metadata in some language tags. I suggest using pseudo-language tags or arrays instead.

For example, Wikimedia uses en-simple for simple English or en-us-tx for Texan English. The advantage over the use of an array is that one needs to decide which one is the default.

**Comment by physikerwelt** [comment]
More example:

https://github.com/w3c/mathml-docs/blob/cb9e988108be0cd216b9f024863cd6f2715d5552/_data/core.yml#L826-L828

^^
It would be good to filter for us vs gb systematically

https://github.com/w3c/mathml-docs/blob/cb9e988108be0cd216b9f024863cd6f2715d5552/_data/core.yml#L935C1-L936C22

^^
Which one is the preferred one?

https://github.com/w3c/mathml-docs/blob/cb9e988108be0cd216b9f024863cd6f2715d5552/_data/core.yml#L1054

^^
Why x?

https://github.com/w3c/mathml-docs/blob/cb9e988108be0cd216b9f024863cd6f2715d5552/_data/core.yml#L1240C1-L1240C36

^^
The arity may be one so no comma may be needed.

https://github.com/w3c/mathml-docs/blob/cb9e988108be0cd216b9f024863cd6f2715d5552/_data/core.yml#L1309
^^
This uses another form of ellipsis (without [ ])

https://github.com/w3c/mathml-docs/blob/cb9e988108be0cd216b9f024863cd6f2715d5552/_data/core.yml#L502
^^
This is not trivial

**Comment by davidcarlisle** [comment]
@physikerwelt  hmm yes

```
      en:
        - "short form American 'tanch $1'"
        - "short form British 'than $1'"
```

I agree that having the metadata mixed with the text template with no makup at all isn't great.

Starting from  where we are I'd suggest using `en` for most English and pulling out `en-gb` as a separate entry, that would require no change to the display scripting as already it shows the `en` field if there is no language-specific entry, so it would mean changing just the few that have a `british` comment to be

```
      en:
        - "short form 'tanch $1'"
      en-gb:
        - "short form 'than $1'"
```

except that as you note in another comment the "short/verbose/.../ metadata is similarly mixed in with the text.

we could have an array for that as well except here there is only one form offered we could offer a long form but I think reading the concept name in full is always an option.  So this could be

```
      en:
        - 'tanch $1'"
      en-gb:
        - "than $1'"
```

or


```
      en:
         - short:
            - 'tanch $1'"
      en-gb:
         - short:
           - "than $1'"
```

or


```
      en:
        -verbose:
            - "hyperbolic tangent"
         - short:
            - 'tanch $1'"
      en-gb:
        -verbose:
            - "hyperbolic tangent"
         - short:
           - "than $1'"
```

@NSoiffer ?
